# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/victo/Desktop/Vivados/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_c_counter_binary_0_0/zsys_c_counter_binary_0_0.xci
# IP: The module: 'zsys_c_counter_binary_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/victo/Desktop/Vivados/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_c_counter_binary_0_0/zsys_c_counter_binary_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zsys_c_counter_binary_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/victo/Desktop/Vivados/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_c_counter_binary_0_0/zsys_c_counter_binary_0_0.xci
# IP: The module: 'zsys_c_counter_binary_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/victo/Desktop/Vivados/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_c_counter_binary_0_0/zsys_c_counter_binary_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zsys_c_counter_binary_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
