# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/victo/Desktop/Vivados/verDAQ8_uart/verDAQ8_uart.srcs/sources_1/bd/zsys/ip/zsys_AXI_ADC_v1_0_0_0/zsys_AXI_ADC_v1_0_0_0.xci
# IP: The module: 'zsys_AXI_ADC_v1_0_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/victo/Desktop/Vivados/verDAQ8_uart/verDAQ8_uart.srcs/sources_1/bd/zsys/ip/zsys_AXI_ADC_v1_0_0_0/src/AXI_ADC_constrains.xdc
# XDC: The top module name and the constraint reference have the same name: 'zsys_AXI_ADC_v1_0_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/victo/Desktop/Vivados/verDAQ8_uart/verDAQ8_uart.srcs/sources_1/bd/zsys/ip/zsys_AXI_ADC_v1_0_0_0/zsys_AXI_ADC_v1_0_0_0.xci
# IP: The module: 'zsys_AXI_ADC_v1_0_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/victo/Desktop/Vivados/verDAQ8_uart/verDAQ8_uart.srcs/sources_1/bd/zsys/ip/zsys_AXI_ADC_v1_0_0_0/src/AXI_ADC_constrains.xdc
# XDC: The top module name and the constraint reference have the same name: 'zsys_AXI_ADC_v1_0_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
