#ifndef __PLATFORM_CONFIG_H_
#define __PLATFORM_CONFIG_H_


#define PLATFORM_EMAC_BASEADDR XPAR_XEMACPS_0_BASEADDR
#define GPIO_DEVICE_ID  XPAR_GPIO_0_DEVICE_ID
#define GPIO_DEVICE_ID1	XPAR_GPIO_1_DEVICE_ID
#define PLATFORM_ZYNQ 


#endif
