# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/victo/Desktop/Vivados/daq_mb_te0716_v7/daq_mb_te0716_v7.srcs/sources_1/bd/zsys/ip/zsys_util_ds_buf_0_0/zsys_util_ds_buf_0_0.xci
# IP: The module: 'zsys_util_ds_buf_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/victo/Desktop/Vivados/daq_mb_te0716_v7/daq_mb_te0716_v7.srcs/sources_1/bd/zsys/ip/zsys_util_ds_buf_0_0/zsys_util_ds_buf_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zsys_util_ds_buf_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/victo/Desktop/Vivados/daq_mb_te0716_v7/daq_mb_te0716_v7.srcs/sources_1/bd/zsys/ip/zsys_util_ds_buf_0_0/zsys_util_ds_buf_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zsys_util_ds_buf_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/victo/Desktop/Vivados/daq_mb_te0716_v7/daq_mb_te0716_v7.srcs/sources_1/bd/zsys/ip/zsys_util_ds_buf_0_0/zsys_util_ds_buf_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zsys_util_ds_buf_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/victo/Desktop/Vivados/daq_mb_te0716_v7/daq_mb_te0716_v7.srcs/sources_1/bd/zsys/ip/zsys_util_ds_buf_0_0/zsys_util_ds_buf_0_0.xci
# IP: The module: 'zsys_util_ds_buf_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/victo/Desktop/Vivados/daq_mb_te0716_v7/daq_mb_te0716_v7.srcs/sources_1/bd/zsys/ip/zsys_util_ds_buf_0_0/zsys_util_ds_buf_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zsys_util_ds_buf_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/victo/Desktop/Vivados/daq_mb_te0716_v7/daq_mb_te0716_v7.srcs/sources_1/bd/zsys/ip/zsys_util_ds_buf_0_0/zsys_util_ds_buf_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zsys_util_ds_buf_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/victo/Desktop/Vivados/daq_mb_te0716_v7/daq_mb_te0716_v7.srcs/sources_1/bd/zsys/ip/zsys_util_ds_buf_0_0/zsys_util_ds_buf_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zsys_util_ds_buf_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
