############################
#DRS4 control signal
############################
#DRS4_Refclk is generated by the SoM and goes to CPLD, then split to each mezzanine board
#set_property -dict {PACKAGE_PIN T2 IOSTANDARD LVDS_25} [get_ports DRS_REFCLK_P]
set_property -dict {PACKAGE_PIN D1 IOSTANDARD LVDS_25} [get_ports DRS_REFCLK_P]

#DRS_A goes to CPLD for mux
#set_property -dict {PACKAGE_PIN B4 IOSTANDARD LVCMOS25} [get_ports {DRS_A[2]}]
#set_property -dict {PACKAGE_PIN A2 IOSTANDARD LVCMOS25} [get_ports {DRS_A[3]}]
#set_property -dict {PACKAGE_PIN B3 IOSTANDARD LVCMOS25} [get_ports {DRS_A[1]}]
#set_property -dict {PACKAGE_PIN D3 IOSTANDARD LVCMOS25} [get_ports {DRS_A[0]}]
set_property -dict {PACKAGE_PIN B2 IOSTANDARD LVCMOS25} [get_ports {DRS_A[3]}]
set_property -dict {PACKAGE_PIN A1 IOSTANDARD LVCMOS25} [get_ports {DRS_A[2]}]
set_property -dict {PACKAGE_PIN A2 IOSTANDARD LVCMOS25} [get_ports {DRS_A[1]}]
set_property -dict {PACKAGE_PIN B4 IOSTANDARD LVCMOS25} [get_ports {DRS_A[0]}]


set_property -dict {PACKAGE_PIN H5 IOSTANDARD LVCMOS25} [get_ports {DRS_DTAP0[0]}]
set_property -dict {PACKAGE_PIN G1 IOSTANDARD LVCMOS25} [get_ports {DRS_DTAP1[0]}]
set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS25} [get_ports {DRS_DTAP2[0]}]
set_property -dict {PACKAGE_PIN C5 IOSTANDARD LVCMOS25} [get_ports {DRS_DTAP3[0]}]
set_property -dict {PACKAGE_PIN H3 IOSTANDARD LVCMOS25} [get_ports {DRS_DTAP4[0]}]

set_property -dict {PACKAGE_PIN A5 IOSTANDARD LVCMOS25} [get_ports {DRS_DWRITE[0]}]
set_property -dict {PACKAGE_PIN H1 IOSTANDARD LVCMOS25} [get_ports {DRS_DWRITE[1]}]
set_property -dict {PACKAGE_PIN E4 IOSTANDARD LVCMOS25} [get_ports {DRS_DWRITE[2]}]
set_property -dict {PACKAGE_PIN C8 IOSTANDARD LVCMOS25} [get_ports {DRS_DWRITE[3]}]
set_property -dict {PACKAGE_PIN H4 IOSTANDARD LVCMOS25} [get_ports {DRS_DWRITE[4]}]


set_property -dict {PACKAGE_PIN A4 IOSTANDARD LVCMOS25} [get_ports {DRS_RSLOAD[0]}]
set_property -dict {PACKAGE_PIN D2 IOSTANDARD LVCMOS25} [get_ports {DRS_RSLOAD[1]}]
set_property -dict {PACKAGE_PIN B6 IOSTANDARD LVCMOS25} [get_ports {DRS_RSLOAD[2]}]
set_property -dict {PACKAGE_PIN B8 IOSTANDARD LVCMOS25} [get_ports {DRS_RSLOAD[3]}]
set_property -dict {PACKAGE_PIN E5 IOSTANDARD LVCMOS25} [get_ports {DRS_RSLOAD[4]}]


set_property -dict {PACKAGE_PIN G3 IOSTANDARD LVCMOS25} [get_ports {DRS_SRCLK[0]}]
set_property -dict {PACKAGE_PIN E2 IOSTANDARD LVCMOS25} [get_ports {DRS_SRCLK[1]}]
set_property -dict {PACKAGE_PIN B7 IOSTANDARD LVCMOS25} [get_ports {DRS_SRCLK[2]}]
set_property -dict {PACKAGE_PIN G7 IOSTANDARD LVCMOS25} [get_ports {DRS_SRCLK[3]}]
set_property -dict {PACKAGE_PIN F5 IOSTANDARD LVCMOS25} [get_ports {DRS_SRCLK[4]}]


#SRIN comes from CPLD as mux signal

#set_property -dict {PACKAGE_PIN A1 IOSTANDARD LVCMOS25} [get_ports DRS_SRIN]
set_property -dict {PACKAGE_PIN B1 IOSTANDARD LVCMOS25} [get_ports DRS_SRIN]

set_property -dict {PACKAGE_PIN G2 IOSTANDARD LVCMOS25} [get_ports {DRS_SROUT[0]}]
set_property -dict {PACKAGE_PIN D7 IOSTANDARD LVCMOS25} [get_ports {DRS_SROUT[1]}]
set_property -dict {PACKAGE_PIN C6 IOSTANDARD LVCMOS25} [get_ports {DRS_SROUT[2]}]
set_property -dict {PACKAGE_PIN G8 IOSTANDARD LVCMOS25} [get_ports {DRS_SROUT[3]}]
set_property -dict {PACKAGE_PIN H6 IOSTANDARD LVCMOS25} [get_ports {DRS_SROUT[4]}]

#DAC i2c communication.

set_property -dict {PACKAGE_PIN F1 IOSTANDARD LVCMOS25} [get_ports I2C_0_scl_io]
set_property -dict {PACKAGE_PIN F2 IOSTANDARD LVCMOS25} [get_ports I2C_0_sda_io]
set_property -dict {PACKAGE_PIN D6 IOSTANDARD LVCMOS25} [get_ports DAC_nCLR]
############################
## ADC SIGNALS
############################
set_property DIFF_TERM TRUE [get_ports LCLK_MUX_N]
set_property -dict {PACKAGE_PIN K4 IOSTANDARD LVDS_25 DIFF_TERM 1 IBUF_LOW_PWR 1} [get_ports LCLK_MUX_P]
set_property DIFF_TERM TRUE [get_ports ADCLK_MUX_N]
set_property -dict {PACKAGE_PIN L5 IOSTANDARD LVDS_25 DIFF_TERM 1 IBUF_LOW_PWR 1} [get_ports ADCLK_MUX_P]
#Inverted polarity ch 1 and ch 2
set_property -dict {PACKAGE_PIN J5 IOSTANDARD LVDS_25 DIFF_TERM 1 IBUF_LOW_PWR 1} [get_ports {MUXOUT_P[0]}]
set_property -dict {PACKAGE_PIN J2 IOSTANDARD LVDS_25 DIFF_TERM 1 IBUF_LOW_PWR 1} [get_ports {MUXOUT_P[1]}]

set_property -dict {PACKAGE_PIN T2 IOSTANDARD LVDS_25 DIFF_TERM 1 IBUF_LOW_PWR 1} [get_ports {MUXOUT_P[2]}]
set_property -dict {PACKAGE_PIN M8 IOSTANDARD LVDS_25 DIFF_TERM 1 IBUF_LOW_PWR 1} [get_ports {MUXOUT_P[3]}]

set_property -dict {PACKAGE_PIN P3 IOSTANDARD LVDS_25 DIFF_TERM 1 IBUF_LOW_PWR 1} [get_ports {MUXOUT_P[4]}]
set_property -dict {PACKAGE_PIN R3 IOSTANDARD LVDS_25 DIFF_TERM 1 IBUF_LOW_PWR 1} [get_ports {MUXOUT_P[5]}]

set_property -dict {PACKAGE_PIN M2 IOSTANDARD LVDS_25 DIFF_TERM 1 IBUF_LOW_PWR 1} [get_ports {MUXOUT_P[6]}]
set_property -dict {PACKAGE_PIN J7 IOSTANDARD LVDS_25 DIFF_TERM 1 IBUF_LOW_PWR 1} [get_ports {MUXOUT_P[7]}]

set_property -dict {PACKAGE_PIN G4 IOSTANDARD LVDS_25} [get_ports ADC_refclk_1_P]
set_property -dict {PACKAGE_PIN A7 IOSTANDARD LVDS_25} [get_ports ADC_refclk_2_P]
set_property -dict {PACKAGE_PIN F7 IOSTANDARD LVDS_25} [get_ports ADC_refclk_3_P]
set_property -dict {PACKAGE_PIN E8 IOSTANDARD LVDS_25} [get_ports ADC_refclk_4_P]
set_property -dict {PACKAGE_PIN G6 IOSTANDARD LVDS_25} [get_ports ADC_refclk_5_P]

#set_property -dict {PACKAGE_PIN C3 IOSTANDARD LVCMOS25} [get_ports ADC_MISO]
#set_property -dict {PACKAGE_PIN D5 IOSTANDARD LVCMOS25} [get_ports ADC_MOSI]
#set_property -dict {PACKAGE_PIN C4 IOSTANDARD LVCMOS25} [get_ports ADC_SCLK]
set_property -dict {PACKAGE_PIN B3 IOSTANDARD LVCMOS25} [get_ports ADC_MISO]
set_property -dict {PACKAGE_PIN D3 IOSTANDARD LVCMOS25} [get_ports ADC_MOSI]
set_property -dict {PACKAGE_PIN C3 IOSTANDARD LVCMOS25} [get_ports ADC_SCLK]

# B0 mezzanina 1
set_property -dict {PACKAGE_PIN Y12 IOSTANDARD LVCMOS25} [get_ports {B0_TRG[7]}]
set_property -dict {PACKAGE_PIN Y13 IOSTANDARD LVCMOS25} [get_ports {B0_TRG[6]}]
set_property -dict {PACKAGE_PIN V16 IOSTANDARD LVCMOS25} [get_ports {B0_TRG[5]}]
set_property -dict {PACKAGE_PIN W16 IOSTANDARD LVCMOS25} [get_ports {B0_TRG[4]}]
set_property -dict {PACKAGE_PIN Y17 IOSTANDARD LVCMOS25} [get_ports {B0_TRG[3]}]
set_property -dict {PACKAGE_PIN W17 IOSTANDARD LVCMOS25} [get_ports {B0_TRG[2]}]
set_property -dict {PACKAGE_PIN AA19 IOSTANDARD LVCMOS25} [get_ports {B0_TRG[1]}]
set_property -dict {PACKAGE_PIN AA20 IOSTANDARD LVCMOS25} [get_ports {B0_TRG[0]}]


#########################
#CPLD control signals
#########################

set_property -dict {PACKAGE_PIN W12 IOSTANDARD LVCMOS25} [get_ports CSR_MOSI]
set_property -dict {PACKAGE_PIN W13 IOSTANDARD LVCMOS25} [get_ports CPLD_MISO]

set_property -dict {PACKAGE_PIN U11 IOSTANDARD LVDS_25} [get_ports CSR_SCLK_P]

set_property -dict {PACKAGE_PIN W15 IOSTANDARD LVCMOS25} [get_ports CSR_nCS]
set_property -dict {PACKAGE_PIN V15 IOSTANDARD LVCMOS25} [get_ports CPLD_nCS]

set_property -dict {PACKAGE_PIN R5 IOSTANDARD LVCMOS25} [get_ports {MUX_SEL[0]}]
set_property -dict {PACKAGE_PIN R4 IOSTANDARD LVCMOS25} [get_ports {MUX_SEL[1]}]
set_property -dict {PACKAGE_PIN N1 IOSTANDARD LVCMOS25} [get_ports {MUX_SEL[2]}]
set_property PULLDOWN true [get_ports {MUX_SEL[2]}]
set_property PULLDOWN true [get_ports {MUX_SEL[1]}]
set_property PULLDOWN true [get_ports {MUX_SEL[0]}]


##########################
## E-link pins
##########################
set_property IOSTANDARD PPDS_25 [get_ports {Elink_clk_P[0]}]
set_property IOSTANDARD PPDS_25 [get_ports {Elink_clk_N[0]}]
set_property PACKAGE_PIN U2 [get_ports {Elink_clk_P[0]}]

set_property DIFF_TERM TRUE [get_ports {Elink_P[0]}]
set_property DIFF_TERM TRUE [get_ports {Elink_N[0]}]
set_property IOSTANDARD PPDS_25 [get_ports {Elink_P[0]}]
set_property IOSTANDARD PPDS_25 [get_ports {Elink_N[0]}]
set_property PACKAGE_PIN L2 [get_ports {Elink_P[0]}]
set_property PACKAGE_PIN L1 [get_ports {Elink_N[0]}]

#set_property PACKAGE_PIN L2 [get_ports Elink_P]
#set_property IOSTANDARD LVDS_25 [get_ports Elink_P]
#set_property IOSTANDARD LVDS_25 [get_ports Elink_N]











