#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# Filename    : zsys.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Fri Dec 13 18:52:04 -03 2024
# SW Build 2258646 on Thu Jun 14 20:02:38 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved. 
#
# usage: zsys.sh [-help]
# usage: zsys.sh [-lib_map_path]
# usage: zsys.sh [-noclean_files]
# usage: zsys.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'zsys.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xil_defaultlib xpm axi_infrastructure_v1_1_0 smartconnect_v1_0 axi_protocol_checker_v2_0_3 axi_vip_v1_1_3 processing_system7_vip_v1_0_5 lib_cdc_v1_0_2 proc_sys_reset_v5_0_12 fifo_generator_v13_2_2 xlconstant_v1_1_5 axi_lite_ipif_v3_0_4 interrupt_control_v3_1_4 axi_gpio_v2_0_19 xbip_utils_v3_0_9 c_reg_fd_v12_0_5 xbip_dsp48_wrapper_v3_0_4 xbip_pipe_v3_0_5 xbip_dsp48_addsub_v3_0_5 xbip_addsub_v3_0_5 c_addsub_v12_0_12 c_gate_bit_v12_0_5 xbip_counter_v3_0_5 c_counter_binary_v12_0_12 xlconcat_v2_1_1 xlslice_v1_0_1 fit_timer_v2_0_8 util_vector_logic_v2_0_1 lib_pkg_v1_0_2 lib_fifo_v1_0_11 lib_srl_fifo_v1_0_2 axi_datamover_v5_1_19 axi_sg_v4_1_10 axi_dma_v7_1_18 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_17 axi_data_fifo_v2_1_16 axi_crossbar_v2_1_18 axi_clock_converter_v2_1_16 axi_protocol_converter_v2_1_17)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "zsys.sh - Script generated by export_simulation (Vivado v2018.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/sc_util_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_checker_v2_0_3 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/03a9/hdl/axi_protocol_checker_v2_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_3 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/b9a8/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_5 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zsys/ip/zsys_processing_system7_0_0/sim/zsys_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zsys/ip/zsys_ADC_readout_buff_0_0/sim/zsys_ADC_readout_buff_0_0.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_ROController_0_0/sim/zsys_ROController_0_0.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_mapper_0_0/sim/zsys_mapper_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_12 $vhdlan_opts \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zsys/ip/zsys_rst_ps7_0_100M_0/sim/zsys_rst_ps7_0_100M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/7aff/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_2 $vhdlan_opts \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zsys/ip/zsys_fifo_generator_0_0/sim/zsys_fifo_generator_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f1c3/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zsys/ip/zsys_xlconstant_1_0/sim/zsys_xlconstant_1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zsys/ip/zsys_proc_sys_reset_0_0/sim/zsys_proc_sys_reset_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zsys/ip/zsys_xlconstant_0_0/sim/zsys_xlconstant_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/cced/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/8e66/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_19 $vhdlan_opts \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/c193/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_gpio_0_0/sim/zsys_axi_gpio_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_utils_v3_0_9 $vhdlan_opts \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/a5f8/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_reg_fd_v12_0_5 $vhdlan_opts \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/cbdd/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/da55/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/442e/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ad9e/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_addsub_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/0e42/hdl/xbip_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_addsub_v12_0_12 $vhdlan_opts \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/7f1a/hdl/c_addsub_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_gate_bit_v12_0_5 $vhdlan_opts \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/693f/hdl/c_gate_bit_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_counter_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/0952/hdl/xbip_counter_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_counter_binary_v12_0_12 $vhdlan_opts \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/c366/hdl/c_counter_binary_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zsys/ip/zsys_c_counter_binary_0_0/sim/zsys_c_counter_binary_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconcat_v2_1_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zsys/ip/zsys_xlconcat_1_0/sim/zsys_xlconcat_1_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlslice_v1_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f3db/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zsys/ip/zsys_xlslice_0_1/sim/zsys_xlslice_0_1.v" \
    "$ref_dir/../../../bd/zsys/ip/zsys_xlslice_1_0/sim/zsys_xlslice_1_0.v" \
    "$ref_dir/../../../bd/zsys/ip/zsys_xlslice_0_2/sim/zsys_xlslice_0_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zsys/ip/zsys_util_ds_buf_1_1/util_ds_buf.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_util_ds_buf_1_1/sim/zsys_util_ds_buf_1_1.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_util_ds_buf_2_0/sim/zsys_util_ds_buf_2_0.vhd" \
    "$ref_dir/../../../bd/zsys/ipshared/00b3/src/drs4_firmware_v5.vhd" \
    "$ref_dir/../../../bd/zsys/ipshared/00b3/src/DRS4_firmware_v2_0_S00_AXI.vhd" \
    "$ref_dir/../../../bd/zsys/ipshared/00b3/src/DRS4_firmware_v2_0.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_DRS4_firmware_1_0/sim/zsys_DRS4_firmware_1_0.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_rst_ps7_0_100M_1/sim/zsys_rst_ps7_0_100M_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zsys/ip/zsys_xlconstant_1_1/sim/zsys_xlconstant_1_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zsys/ipshared/e524/hdl/dac_i2c_v1_0_S00_AXI.vhd" \
    "$ref_dir/../../../bd/zsys/ipshared/e524/src/i2c_control.vhd" \
    "$ref_dir/../../../bd/zsys/ipshared/e524/src/i2c_dac.vhd" \
    "$ref_dir/../../../bd/zsys/ipshared/e524/hdl/dac_i2c_v1_0.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_dac_i2c_0_0/sim/zsys_dac_i2c_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work fit_timer_v2_0_8 $vhdlan_opts \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/d59c/hdl/fit_timer_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zsys/ip/zsys_fit_timer_0_0/sim/zsys_fit_timer_0_0.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_reset_init_0_0/sim/zsys_reset_init_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zsys/ip/zsys_xlslice_10_0/sim/zsys_xlslice_10_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zsys/ip/zsys_trigger_logic_0_0/sim/zsys_trigger_logic_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zsys/ip/zsys_xlslice_2_0/sim/zsys_xlslice_2_0.v" \
    "$ref_dir/../../../bd/zsys/ip/zsys_xlslice_2_1/sim/zsys_xlslice_2_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work util_vector_logic_v2_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/2137/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zsys/ip/zsys_util_vector_logic_0_0/sim/zsys_util_vector_logic_0_0.v" \
    "$ref_dir/../../../bd/zsys/ip/zsys_util_vector_logic_0_1/sim/zsys_util_vector_logic_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zsys/ip/zsys_M1to5_0_0/sim/zsys_M1to5_0_0.vhd" \
    "$ref_dir/../../../bd/zsys/ipshared/edit_CPLD_ctrl_v1_0.srcs/sources_1/new/CPLD_comm_module.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_CPLD_ctrl_0_0/sim/zsys_CPLD_ctrl_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zsys/ip/zsys_fifo8b_2_axis_0_0/src/fifo_generator_1/sim/fifo_generator_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zsys/ipshared/76d2/hdl/fifo8b_2_axis_v1_0_M00_AXIS.vhd" \
    "$ref_dir/../../../bd/zsys/ipshared/76d2/hdl/fifo8b_2_axis_v1_0.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_fifo8b_2_axis_0_0/sim/zsys_fifo8b_2_axis_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_fifo_v1_0_11 $vhdlan_opts \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/6078/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_19 $vhdlan_opts \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec8a/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_sg_v4_1_10 $vhdlan_opts \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/6e5f/hdl/axi_sg_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_dma_v7_1_18 $vhdlan_opts \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/6bfe/hdl/axi_dma_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_dma_0_0/sim/zsys_axi_dma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_smc_0/bd_0/sim/bd_fa8c.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5160/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_10/sim/bd_fa8c_s00a2s_0.sv" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_19/sim/bd_fa8c_s01a2s_0.sv" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_25/sim/bd_fa8c_s02a2s_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/acc2/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_29/sim/bd_fa8c_m00s2a_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/28cb/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_35/sim/bd_fa8c_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_30/sim/bd_fa8c_m00arn_0.sv" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_31/sim/bd_fa8c_m00rn_0.sv" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_32/sim/bd_fa8c_m00awn_0.sv" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_33/sim/bd_fa8c_m00wn_0.sv" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_34/sim/bd_fa8c_m00bn_0.sv" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_26/sim/bd_fa8c_sawn_1.sv" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_27/sim/bd_fa8c_swn_1.sv" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_28/sim/bd_fa8c_sbn_1.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/afa8/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_22/sim/bd_fa8c_s02mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/4521/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_23/sim/bd_fa8c_s02tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/d1fc/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_24/sim/bd_fa8c_s02sic_0.sv" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_20/sim/bd_fa8c_sarn_1.sv" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_21/sim/bd_fa8c_srn_1.sv" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_16/sim/bd_fa8c_s01mmu_0.sv" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_17/sim/bd_fa8c_s01tr_0.sv" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_18/sim/bd_fa8c_s01sic_0.sv" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_11/sim/bd_fa8c_sarn_0.sv" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_12/sim/bd_fa8c_srn_0.sv" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_13/sim/bd_fa8c_sawn_0.sv" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_14/sim/bd_fa8c_swn_0.sv" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_15/sim/bd_fa8c_sbn_0.sv" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_7/sim/bd_fa8c_s00mmu_0.sv" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_8/sim/bd_fa8c_s00tr_0.sv" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_9/sim/bd_fa8c_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/4e7b/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_2/sim/bd_fa8c_arsw_0.sv" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_3/sim/bd_fa8c_rsw_0.sv" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_4/sim/bd_fa8c_awsw_0.sv" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_5/sim/bd_fa8c_wsw_0.sv" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_6/sim/bd_fa8c_bsw_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_0/sim/bd_fa8c_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_1/sim/bd_fa8c_psr_aclk_0.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_smc_0/sim/zsys_axi_smc_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zsys/ip/zsys_xlconcat_0_0/sim/zsys_xlconcat_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zsys/ip/zsys_M1to5_0_1/sim/zsys_M1to5_0_1.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_M1to5_0_2/sim/zsys_M1to5_0_2.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_util_ds_buf_2_1/sim/zsys_util_ds_buf_2_1.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_util_ds_buf_4_0/sim/zsys_util_ds_buf_4_0.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_util_ds_buf_4_1/sim/zsys_util_ds_buf_4_1.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_util_ds_buf_4_2/sim/zsys_util_ds_buf_4_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/6020/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/247d/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_18 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/15a3/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zsys/ip/zsys_xbar_0/sim/zsys_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zsys/ip/zsys_util_ds_buf_3_1/sim/zsys_util_ds_buf_3_1.vhd" \
    "$ref_dir/../../../bd/zsys/sim/zsys.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_Signal_sel_1_0/sim/zsys_Signal_sel_1_0.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_util_ds_buf_0_1/sim/zsys_util_ds_buf_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zsys/ip/zsys_xlconstant_2_1/sim/zsys_xlconstant_2_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zsys/ip/zsys_enable_signal_0_0/sim/zsys_enable_signal_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zsys/ip/zsys_xlslice_12to14_0/sim/zsys_xlslice_12to14_0.v" \
    "$ref_dir/../../../bd/zsys/ip/zsys_xlslice_3to3_0/sim/zsys_xlslice_3to3_0.v" \
    "$ref_dir/../../../bd/zsys/ip/zsys_xlconcat_1_1/sim/zsys_xlconcat_1_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zsys/ip/zsys_util_ds_buf_ADCLK_0/sim/zsys_util_ds_buf_ADCLK_0.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_c_counter_binary_0_1/sim/zsys_c_counter_binary_0_1.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_delay_module_0_0/sim/zsys_delay_module_0_0.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_axi_gpio_1_0/sim/zsys_axi_gpio_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zsys/ip/zsys_xlslice_2_2/sim/zsys_xlslice_2_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zsys/ip/zsys_delay_module_0_1/sim/zsys_delay_module_0_1.vhd" \
    "$ref_dir/../../../bd/zsys/ipshared/b2a8/hdl/clk_mon_v1_0_S00_AXI.vhd" \
    "$ref_dir/../../../bd/zsys/ipshared/b2a8/src/clk_monitor.vhd" \
    "$ref_dir/../../../bd/zsys/ipshared/b2a8/hdl/clk_mon_v1_0.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_clk_mon_0_0/sim/zsys_clk_mon_0_0.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_Vibufds_diff_out_0_0/sim/zsys_Vibufds_diff_out_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zsys/ip/zsys_xlconstant_1_2/sim/zsys_xlconstant_1_2.v" \
    "$ref_dir/../../../bd/zsys/ip/zsys_xlconcat_3_0/sim/zsys_xlconcat_3_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zsys/ip/zsys_DRS_A_test_0_0/sim/zsys_DRS_A_test_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zsys/ip/zsys_xlslice_3to3_1/sim/zsys_xlslice_3to3_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zsys/ip/zsys_Elink_output_0_0/sim/zsys_Elink_output_0_0.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_util_ds_buf_0_0/sim/zsys_util_ds_buf_0_0.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_util_ds_buf_0_2/sim/zsys_util_ds_buf_0_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zsys/ip/zsys_xlslice_3to3_2/sim/zsys_xlslice_3to3_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zsys/ip/zsys_Lvds_Rx_top_0_0/sim/zsys_Lvds_Rx_top_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zsys/ip/zsys_util_vector_logic_2_0_1/sim/zsys_util_vector_logic_2_0.v" \
    "$ref_dir/../../../bd/zsys/ip/zsys_util_vector_logic_0_2/sim/zsys_util_vector_logic_0_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zsys/ipshared/a552/hdl/AXI_ADC_v3_0_S00_AXI.vhd" \
    "$ref_dir/../../../bd/zsys/ipshared/a552/src/SPI_core_v2.vhd" \
    "$ref_dir/../../../bd/zsys/ipshared/a552/src/ADC_ctrl.vhd" \
    "$ref_dir/../../../bd/zsys/ipshared/a552/src/ADC_readout_3.vhd" \
    "$ref_dir/../../../bd/zsys/ipshared/a552/hdl/AXI_ADC_v3_0.vhd" \
    "$ref_dir/../../../bd/zsys/ip/zsys_AXI_ADC_1_0/sim/zsys_AXI_ADC_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_clock_converter_v2_1_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/e9a5/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zsys/ip/zsys_auto_cc_0/sim/zsys_auto_cc_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ccfb/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../CMB40_v1.srcs/sources_1/bd/zsys/ipshared/f90c/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zsys/ip/zsys_auto_pc_0/sim/zsys_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.zsys xil_defaultlib.glbl -o zsys_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./zsys_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./zsys.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key zsys_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc zsys_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./zsys.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: zsys.sh [-help]\n\
Usage: zsys.sh [-lib_map_path]\n\
Usage: zsys.sh [-reset_run]\n\
Usage: zsys.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
