# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/timing.xdc

# XDC: imports/constraints/_i_unused_io.xdc

# XDC: new/CMB40_TE0715.xdc

# Block Designs: bd/zsys/zsys.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys || ORIG_REF_NAME==zsys} -quiet] -quiet

# IP: bd/zsys/ip/zsys_processing_system7_0_0/zsys_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_processing_system7_0_0 || ORIG_REF_NAME==zsys_processing_system7_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_ADC_readout_buff_0_0/zsys_ADC_readout_buff_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_ADC_readout_buff_0_0 || ORIG_REF_NAME==zsys_ADC_readout_buff_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_ROController_0_0/zsys_ROController_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_ROController_0_0 || ORIG_REF_NAME==zsys_ROController_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_mapper_0_0/zsys_mapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_mapper_0_0 || ORIG_REF_NAME==zsys_mapper_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_rst_ps7_0_100M_0/zsys_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_rst_ps7_0_100M_0 || ORIG_REF_NAME==zsys_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_ps7_0_axi_periph_0/zsys_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_ps7_0_axi_periph_0 || ORIG_REF_NAME==zsys_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_fifo_generator_0_0/zsys_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_fifo_generator_0_0 || ORIG_REF_NAME==zsys_fifo_generator_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xlconstant_1_0/zsys_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xlconstant_1_0 || ORIG_REF_NAME==zsys_xlconstant_1_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_proc_sys_reset_0_0/zsys_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_proc_sys_reset_0_0 || ORIG_REF_NAME==zsys_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xlconstant_0_0/zsys_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xlconstant_0_0 || ORIG_REF_NAME==zsys_xlconstant_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_axi_gpio_0_0/zsys_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_axi_gpio_0_0 || ORIG_REF_NAME==zsys_axi_gpio_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_c_counter_binary_0_0/zsys_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_c_counter_binary_0_0 || ORIG_REF_NAME==zsys_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xlconcat_1_0/zsys_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xlconcat_1_0 || ORIG_REF_NAME==zsys_xlconcat_1_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xlslice_0_1/zsys_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xlslice_0_1 || ORIG_REF_NAME==zsys_xlslice_0_1} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xlslice_1_0/zsys_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xlslice_1_0 || ORIG_REF_NAME==zsys_xlslice_1_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xlslice_0_2/zsys_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xlslice_0_2 || ORIG_REF_NAME==zsys_xlslice_0_2} -quiet] -quiet

# IP: bd/zsys/ip/zsys_util_ds_buf_1_1/zsys_util_ds_buf_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_util_ds_buf_1_1 || ORIG_REF_NAME==zsys_util_ds_buf_1_1} -quiet] -quiet

# IP: bd/zsys/ip/zsys_util_ds_buf_2_0/zsys_util_ds_buf_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_util_ds_buf_2_0 || ORIG_REF_NAME==zsys_util_ds_buf_2_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_DRS4_firmware_1_0/zsys_DRS4_firmware_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_DRS4_firmware_1_0 || ORIG_REF_NAME==zsys_DRS4_firmware_1_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_rst_ps7_0_100M_1/zsys_rst_ps7_0_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_rst_ps7_0_100M_1 || ORIG_REF_NAME==zsys_rst_ps7_0_100M_1} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xlconstant_1_1/zsys_xlconstant_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xlconstant_1_1 || ORIG_REF_NAME==zsys_xlconstant_1_1} -quiet] -quiet

# IP: bd/zsys/ip/zsys_dac_i2c_0_0/zsys_dac_i2c_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_dac_i2c_0_0 || ORIG_REF_NAME==zsys_dac_i2c_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_fit_timer_0_0/zsys_fit_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_fit_timer_0_0 || ORIG_REF_NAME==zsys_fit_timer_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_reset_init_0_0/zsys_reset_init_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_reset_init_0_0 || ORIG_REF_NAME==zsys_reset_init_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xlslice_10_0/zsys_xlslice_10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xlslice_10_0 || ORIG_REF_NAME==zsys_xlslice_10_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_trigger_logic_0_0/zsys_trigger_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_trigger_logic_0_0 || ORIG_REF_NAME==zsys_trigger_logic_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xlslice_2_0/zsys_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xlslice_2_0 || ORIG_REF_NAME==zsys_xlslice_2_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xlslice_2_1/zsys_xlslice_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xlslice_2_1 || ORIG_REF_NAME==zsys_xlslice_2_1} -quiet] -quiet

# IP: bd/zsys/ip/zsys_util_vector_logic_0_0/zsys_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_util_vector_logic_0_0 || ORIG_REF_NAME==zsys_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_util_vector_logic_0_1/zsys_util_vector_logic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_util_vector_logic_0_1 || ORIG_REF_NAME==zsys_util_vector_logic_0_1} -quiet] -quiet

# IP: bd/zsys/ip/zsys_M1to5_0_0/zsys_M1to5_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_M1to5_0_0 || ORIG_REF_NAME==zsys_M1to5_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_CPLD_ctrl_0_0/zsys_CPLD_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_CPLD_ctrl_0_0 || ORIG_REF_NAME==zsys_CPLD_ctrl_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_fifo8b_2_axis_0_0/zsys_fifo8b_2_axis_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_fifo8b_2_axis_0_0 || ORIG_REF_NAME==zsys_fifo8b_2_axis_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_axi_dma_0_0/zsys_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_axi_dma_0_0 || ORIG_REF_NAME==zsys_axi_dma_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_axi_smc_0/zsys_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_axi_smc_0 || ORIG_REF_NAME==zsys_axi_smc_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xlconcat_0_0/zsys_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xlconcat_0_0 || ORIG_REF_NAME==zsys_xlconcat_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_M1to5_0_1/zsys_M1to5_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_M1to5_0_1 || ORIG_REF_NAME==zsys_M1to5_0_1} -quiet] -quiet

# IP: bd/zsys/ip/zsys_M1to5_0_2/zsys_M1to5_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_M1to5_0_2 || ORIG_REF_NAME==zsys_M1to5_0_2} -quiet] -quiet

# IP: bd/zsys/ip/zsys_util_ds_buf_2_1/zsys_util_ds_buf_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_util_ds_buf_2_1 || ORIG_REF_NAME==zsys_util_ds_buf_2_1} -quiet] -quiet

# IP: bd/zsys/ip/zsys_util_ds_buf_4_0/zsys_util_ds_buf_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_util_ds_buf_4_0 || ORIG_REF_NAME==zsys_util_ds_buf_4_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_util_ds_buf_4_1/zsys_util_ds_buf_4_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_util_ds_buf_4_1 || ORIG_REF_NAME==zsys_util_ds_buf_4_1} -quiet] -quiet

# IP: bd/zsys/ip/zsys_util_ds_buf_4_2/zsys_util_ds_buf_4_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_util_ds_buf_4_2 || ORIG_REF_NAME==zsys_util_ds_buf_4_2} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xbar_0/zsys_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xbar_0 || ORIG_REF_NAME==zsys_xbar_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_util_ds_buf_3_1/zsys_util_ds_buf_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_util_ds_buf_3_1 || ORIG_REF_NAME==zsys_util_ds_buf_3_1} -quiet] -quiet

# IP: bd/zsys/ip/zsys_Signal_sel_1_0/zsys_Signal_sel_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_Signal_sel_1_0 || ORIG_REF_NAME==zsys_Signal_sel_1_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_util_ds_buf_0_1/zsys_util_ds_buf_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_util_ds_buf_0_1 || ORIG_REF_NAME==zsys_util_ds_buf_0_1} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xlconstant_2_1/zsys_xlconstant_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xlconstant_2_1 || ORIG_REF_NAME==zsys_xlconstant_2_1} -quiet] -quiet

# IP: bd/zsys/ip/zsys_enable_signal_0_0/zsys_enable_signal_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_enable_signal_0_0 || ORIG_REF_NAME==zsys_enable_signal_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xlslice_12to14_0/zsys_xlslice_12to14_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xlslice_12to14_0 || ORIG_REF_NAME==zsys_xlslice_12to14_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xlslice_3to3_0/zsys_xlslice_3to3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xlslice_3to3_0 || ORIG_REF_NAME==zsys_xlslice_3to3_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xlconcat_1_1/zsys_xlconcat_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xlconcat_1_1 || ORIG_REF_NAME==zsys_xlconcat_1_1} -quiet] -quiet

# IP: bd/zsys/ip/zsys_util_ds_buf_ADCLK_0/zsys_util_ds_buf_ADCLK_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_util_ds_buf_ADCLK_0 || ORIG_REF_NAME==zsys_util_ds_buf_ADCLK_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_c_counter_binary_0_1/zsys_c_counter_binary_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_c_counter_binary_0_1 || ORIG_REF_NAME==zsys_c_counter_binary_0_1} -quiet] -quiet

# IP: bd/zsys/ip/zsys_delay_module_0_0/zsys_delay_module_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_delay_module_0_0 || ORIG_REF_NAME==zsys_delay_module_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_axi_gpio_1_0/zsys_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_axi_gpio_1_0 || ORIG_REF_NAME==zsys_axi_gpio_1_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xlslice_2_2/zsys_xlslice_2_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xlslice_2_2 || ORIG_REF_NAME==zsys_xlslice_2_2} -quiet] -quiet

# IP: bd/zsys/ip/zsys_delay_module_0_1/zsys_delay_module_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_delay_module_0_1 || ORIG_REF_NAME==zsys_delay_module_0_1} -quiet] -quiet

# IP: bd/zsys/ip/zsys_clk_mon_0_0/zsys_clk_mon_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_clk_mon_0_0 || ORIG_REF_NAME==zsys_clk_mon_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_Vibufds_diff_out_0_0/zsys_Vibufds_diff_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_Vibufds_diff_out_0_0 || ORIG_REF_NAME==zsys_Vibufds_diff_out_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xlconstant_1_2/zsys_xlconstant_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xlconstant_1_2 || ORIG_REF_NAME==zsys_xlconstant_1_2} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xlconcat_3_0/zsys_xlconcat_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xlconcat_3_0 || ORIG_REF_NAME==zsys_xlconcat_3_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_DRS_A_test_0_0/zsys_DRS_A_test_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_DRS_A_test_0_0 || ORIG_REF_NAME==zsys_DRS_A_test_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xlslice_3to3_1/zsys_xlslice_3to3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xlslice_3to3_1 || ORIG_REF_NAME==zsys_xlslice_3to3_1} -quiet] -quiet

# IP: bd/zsys/ip/zsys_Elink_output_0_0/zsys_Elink_output_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_Elink_output_0_0 || ORIG_REF_NAME==zsys_Elink_output_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_util_ds_buf_0_0/zsys_util_ds_buf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_util_ds_buf_0_0 || ORIG_REF_NAME==zsys_util_ds_buf_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_util_ds_buf_0_2/zsys_util_ds_buf_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_util_ds_buf_0_2 || ORIG_REF_NAME==zsys_util_ds_buf_0_2} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xlslice_3to3_2/zsys_xlslice_3to3_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xlslice_3to3_2 || ORIG_REF_NAME==zsys_xlslice_3to3_2} -quiet] -quiet

# IP: bd/zsys/ip/zsys_Lvds_Rx_top_0_0/zsys_Lvds_Rx_top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_Lvds_Rx_top_0_0 || ORIG_REF_NAME==zsys_Lvds_Rx_top_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_util_vector_logic_2_0_1/zsys_util_vector_logic_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_util_vector_logic_2_0 || ORIG_REF_NAME==zsys_util_vector_logic_2_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_util_vector_logic_0_2/zsys_util_vector_logic_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_util_vector_logic_0_2 || ORIG_REF_NAME==zsys_util_vector_logic_0_2} -quiet] -quiet

# IP: bd/zsys/ip/zsys_AXI_ADC_1_0/zsys_AXI_ADC_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_AXI_ADC_1_0 || ORIG_REF_NAME==zsys_AXI_ADC_1_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_auto_cc_0/zsys_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_auto_cc_0 || ORIG_REF_NAME==zsys_auto_cc_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_auto_pc_0/zsys_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_auto_pc_0 || ORIG_REF_NAME==zsys_auto_pc_0} -quiet] -quiet

# XDC: bd/zsys/zsys_ooc.xdc
