# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/timing.xdc

# XDC: imports/constraints/_i_unused_io.xdc

# XDC: imports/new/TE0715.xdc

# Block Designs: bd/zsys/zsys.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys || ORIG_REF_NAME==zsys} -quiet] -quiet

# IP: bd/zsys/ip/zsys_processing_system7_0_0/zsys_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_processing_system7_0_0 || ORIG_REF_NAME==zsys_processing_system7_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_AXI_ADC_v1_0_0_0/zsys_AXI_ADC_v1_0_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_AXI_ADC_v1_0_0_0 || ORIG_REF_NAME==zsys_AXI_ADC_v1_0_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_ADC_readout_buff_0_0/zsys_ADC_readout_buff_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_ADC_readout_buff_0_0 || ORIG_REF_NAME==zsys_ADC_readout_buff_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_ROController_0_0/zsys_ROController_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_ROController_0_0 || ORIG_REF_NAME==zsys_ROController_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_mapper_0_0/zsys_mapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_mapper_0_0 || ORIG_REF_NAME==zsys_mapper_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_rst_ps7_0_100M_0/zsys_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_rst_ps7_0_100M_0 || ORIG_REF_NAME==zsys_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_ps7_0_axi_periph_0/zsys_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_ps7_0_axi_periph_0 || ORIG_REF_NAME==zsys_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_fifo_generator_0_0/zsys_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_fifo_generator_0_0 || ORIG_REF_NAME==zsys_fifo_generator_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xbar_0/zsys_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xbar_0 || ORIG_REF_NAME==zsys_xbar_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xlconstant_1_0/zsys_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xlconstant_1_0 || ORIG_REF_NAME==zsys_xlconstant_1_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_util_ds_buf_0_0/zsys_util_ds_buf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_util_ds_buf_0_0 || ORIG_REF_NAME==zsys_util_ds_buf_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_proc_sys_reset_0_0/zsys_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_proc_sys_reset_0_0 || ORIG_REF_NAME==zsys_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xlconstant_0_0/zsys_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xlconstant_0_0 || ORIG_REF_NAME==zsys_xlconstant_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_axi_gpio_0_0/zsys_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_axi_gpio_0_0 || ORIG_REF_NAME==zsys_axi_gpio_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_c_counter_binary_0_0/zsys_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_c_counter_binary_0_0 || ORIG_REF_NAME==zsys_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xlconcat_1_0/zsys_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xlconcat_1_0 || ORIG_REF_NAME==zsys_xlconcat_1_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xlslice_0_1/zsys_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xlslice_0_1 || ORIG_REF_NAME==zsys_xlslice_0_1} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xlslice_1_0/zsys_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xlslice_1_0 || ORIG_REF_NAME==zsys_xlslice_1_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xlslice_0_2/zsys_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xlslice_0_2 || ORIG_REF_NAME==zsys_xlslice_0_2} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xlslice_0_3/zsys_xlslice_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xlslice_0_3 || ORIG_REF_NAME==zsys_xlslice_0_3} -quiet] -quiet

# IP: bd/zsys/ip/zsys_util_ds_buf_1_1/zsys_util_ds_buf_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_util_ds_buf_1_1 || ORIG_REF_NAME==zsys_util_ds_buf_1_1} -quiet] -quiet

# IP: bd/zsys/ip/zsys_util_ds_buf_2_0/zsys_util_ds_buf_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_util_ds_buf_2_0 || ORIG_REF_NAME==zsys_util_ds_buf_2_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_DRS4_firmware_1_0/zsys_DRS4_firmware_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_DRS4_firmware_1_0 || ORIG_REF_NAME==zsys_DRS4_firmware_1_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_rst_ps7_0_100M_1/zsys_rst_ps7_0_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_rst_ps7_0_100M_1 || ORIG_REF_NAME==zsys_rst_ps7_0_100M_1} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xlconstant_1_1/zsys_xlconstant_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xlconstant_1_1 || ORIG_REF_NAME==zsys_xlconstant_1_1} -quiet] -quiet

# IP: bd/zsys/ip/zsys_dac_i2c_0_0/zsys_dac_i2c_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_dac_i2c_0_0 || ORIG_REF_NAME==zsys_dac_i2c_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xlconstant_3_0/zsys_xlconstant_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xlconstant_3_0 || ORIG_REF_NAME==zsys_xlconstant_3_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_fifo2Uart_0_1/zsys_fifo2Uart_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_fifo2Uart_0_1 || ORIG_REF_NAME==zsys_fifo2Uart_0_1} -quiet] -quiet

# IP: bd/zsys/ip/zsys_fifo_generator_1_0/zsys_fifo_generator_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_fifo_generator_1_0 || ORIG_REF_NAME==zsys_fifo_generator_1_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_fit_timer_0_0/zsys_fit_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_fit_timer_0_0 || ORIG_REF_NAME==zsys_fit_timer_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xlslice_1_1/zsys_xlslice_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xlslice_1_1 || ORIG_REF_NAME==zsys_xlslice_1_1} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xlslice_5to6_0/zsys_xlslice_5to6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xlslice_5to6_0 || ORIG_REF_NAME==zsys_xlslice_5to6_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xlslice_7to8_0/zsys_xlslice_7to8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xlslice_7to8_0 || ORIG_REF_NAME==zsys_xlslice_7to8_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xlslice_7to8_1/zsys_xlslice_7to8_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xlslice_7to8_1 || ORIG_REF_NAME==zsys_xlslice_7to8_1} -quiet] -quiet

# IP: bd/zsys/ip/zsys_reset_init_0_0/zsys_reset_init_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_reset_init_0_0 || ORIG_REF_NAME==zsys_reset_init_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xlslice_10_0/zsys_xlslice_10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xlslice_10_0 || ORIG_REF_NAME==zsys_xlslice_10_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_util_ds_buf_0_1/zsys_util_ds_buf_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_util_ds_buf_0_1 || ORIG_REF_NAME==zsys_util_ds_buf_0_1} -quiet] -quiet

# IP: bd/zsys/ip/zsys_auto_cc_0/zsys_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_auto_cc_0 || ORIG_REF_NAME==zsys_auto_cc_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_auto_pc_0/zsys_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_auto_pc_0 || ORIG_REF_NAME==zsys_auto_pc_0} -quiet] -quiet

# XDC: bd/zsys/zsys_ooc.xdc
