# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z015clg485-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir c:/users/victo/desktop/vivados/cmb40_v1/cmb40_v1.tmp/axi_adc_v1_0_v2_0_project/AXI_ADC_v1_0_v2_0_project.cache/wt [current_project]
set_property parent.project_path c:/users/victo/desktop/vivados/cmb40_v1/cmb40_v1.tmp/axi_adc_v1_0_v2_0_project/AXI_ADC_v1_0_v2_0_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part trenz.biz:te0715_15_2i:part0:1.1 [current_project]
set_property ip_repo_paths c:/Users/victo/Desktop/Vivados/ip_lib [current_project]
set_property ip_output_repo c:/users/victo/desktop/vivados/cmb40_v1/cmb40_v1.tmp/axi_adc_v1_0_v2_0_project/AXI_ADC_v1_0_v2_0_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  c:/Users/victo/Desktop/Vivados/ip_lib/axi_adc_2.0/src/SPI_core_v2.vhd
  c:/Users/victo/Desktop/Vivados/ip_lib/axi_adc_2.0/src/ADC_ctrl.vhd
  c:/Users/victo/Desktop/Vivados/ip_lib/axi_adc_2.0/src/ADC_readout_2.vhd
  c:/Users/victo/Desktop/Vivados/ip_lib/axi_adc_2.0/src/AXI_ADC_v1_0_S00_AXI_ctrl.vhd
  c:/Users/victo/Desktop/Vivados/ip_lib/axi_adc_2.0/src/AXI_ADC_v1_0.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc c:/Users/victo/Desktop/Vivados/ip_lib/axi_adc_2.0/src/AXI_ADC_constrains.xdc
set_property used_in_implementation false [get_files c:/Users/victo/Desktop/Vivados/ip_lib/axi_adc_2.0/src/AXI_ADC_constrains.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top AXI_ADC_v1_0 -part xc7z015clg485-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef AXI_ADC_v1_0.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file AXI_ADC_v1_0_utilization_synth.rpt -pb AXI_ADC_v1_0_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
