# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/zsys_axi_smc_0.xci
# IP: The module: 'zsys_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/bd_fa8c.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_10/bd_fa8c_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_19/bd_fa8c_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_25/bd_fa8c_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_29/bd_fa8c_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_35/bd_fa8c_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_30/bd_fa8c_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_31/bd_fa8c_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_32/bd_fa8c_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_33/bd_fa8c_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_34/bd_fa8c_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_26/bd_fa8c_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_27/bd_fa8c_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_28/bd_fa8c_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_22/bd_fa8c_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_23/bd_fa8c_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_24/bd_fa8c_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_20/bd_fa8c_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_21/bd_fa8c_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_16/bd_fa8c_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_17/bd_fa8c_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_18/bd_fa8c_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_11/bd_fa8c_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_12/bd_fa8c_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_13/bd_fa8c_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_14/bd_fa8c_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_15/bd_fa8c_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_7/bd_fa8c_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_8/bd_fa8c_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_9/bd_fa8c_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_2/bd_fa8c_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_3/bd_fa8c_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_4/bd_fa8c_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_5/bd_fa8c_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_6/bd_fa8c_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_0/bd_fa8c_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_1/bd_fa8c_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_10/bd_fa8c_s00a2s_0_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_19/bd_fa8c_s01a2s_0_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_25/bd_fa8c_s02a2s_0_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_29/bd_fa8c_m00s2a_0_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_30/bd_fa8c_m00arn_0_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_31/bd_fa8c_m00rn_0_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_32/bd_fa8c_m00awn_0_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_33/bd_fa8c_m00wn_0_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_34/bd_fa8c_m00bn_0_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_26/bd_fa8c_sawn_1_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_27/bd_fa8c_swn_1_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_28/bd_fa8c_sbn_1_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_20/bd_fa8c_sarn_1_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_21/bd_fa8c_srn_1_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_11/bd_fa8c_sarn_0_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_12/bd_fa8c_srn_0_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_13/bd_fa8c_sawn_0_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_14/bd_fa8c_swn_0_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_15/bd_fa8c_sbn_0_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_2/bd_fa8c_arsw_0_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_3/bd_fa8c_rsw_0_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_4/bd_fa8c_awsw_0_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_5/bd_fa8c_wsw_0_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_6/bd_fa8c_bsw_0_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_1/bd_fa8c_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_1/bd_fa8c_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zsys_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/zsys_axi_smc_0.xci
# IP: The module: 'zsys_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/bd_fa8c.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_10/bd_fa8c_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_19/bd_fa8c_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_25/bd_fa8c_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_29/bd_fa8c_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_35/bd_fa8c_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_30/bd_fa8c_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_31/bd_fa8c_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_32/bd_fa8c_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_33/bd_fa8c_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_34/bd_fa8c_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_26/bd_fa8c_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_27/bd_fa8c_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_28/bd_fa8c_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_22/bd_fa8c_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_23/bd_fa8c_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_24/bd_fa8c_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_20/bd_fa8c_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_21/bd_fa8c_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_16/bd_fa8c_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_17/bd_fa8c_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_18/bd_fa8c_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_11/bd_fa8c_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_12/bd_fa8c_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_13/bd_fa8c_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_14/bd_fa8c_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_15/bd_fa8c_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_7/bd_fa8c_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_8/bd_fa8c_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_9/bd_fa8c_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_2/bd_fa8c_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_3/bd_fa8c_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_4/bd_fa8c_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_5/bd_fa8c_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_6/bd_fa8c_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_0/bd_fa8c_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_1/bd_fa8c_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_10/bd_fa8c_s00a2s_0_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_19/bd_fa8c_s01a2s_0_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_25/bd_fa8c_s02a2s_0_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_29/bd_fa8c_m00s2a_0_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_30/bd_fa8c_m00arn_0_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_31/bd_fa8c_m00rn_0_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_32/bd_fa8c_m00awn_0_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_33/bd_fa8c_m00wn_0_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_34/bd_fa8c_m00bn_0_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_26/bd_fa8c_sawn_1_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_27/bd_fa8c_swn_1_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_28/bd_fa8c_sbn_1_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_20/bd_fa8c_sarn_1_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_21/bd_fa8c_srn_1_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_11/bd_fa8c_sarn_0_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_12/bd_fa8c_srn_0_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_13/bd_fa8c_sawn_0_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_14/bd_fa8c_swn_0_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_15/bd_fa8c_sbn_0_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_2/bd_fa8c_arsw_0_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_3/bd_fa8c_rsw_0_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_4/bd_fa8c_awsw_0_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_5/bd_fa8c_wsw_0_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_6/bd_fa8c_bsw_0_ooc.xdc

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_1/bd_fa8c_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/bd_0/ip/ip_1/bd_fa8c_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/ifraba/Desktop/Laboral/SAPHIR/Pruebas_tecnicas/CMB_project/CMB_project_Gitlab_Orlando/charge-monitoring-system/zynq/CMB40_v1/CMB40_v1.srcs/sources_1/bd/zsys/ip/zsys_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zsys_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
