#ifndef __PLATFORM_CONFIG_H_
#define __PLATFORM_CONFIG_H_


#define PLATFORM_EMAC_BASEADDR XPAR_XEMACPS_0_BASEADDR
#define UART_DEVICE_ID 0
#define PLATFORM_ZYNQ 
#define GPIO_DEVICE_ID  XPAR_GPIO_0_DEVICE_ID

#endif
